### ISSUE TITLE
Fix Pull Request Issue#35

### ISSUE THREAD

**Issue by PhongTran98** [antonio-do/eardrum#39]
- [x] Change tabs order and change "Others" tab to "User Guides"
- [x] Fix 'Warning: Each child in a list should have a unique "key" prop'
- [x] Enable/disable filter for some columns
- [x] Readjust column width, make it so that column label can be shown multiline
- [x] Make smaller action button 
- [x] Use chip for confirmation detail
- [x] Merge half-day column into start/end date columns
- [x] Add rejecting reason

**Comment by antonio-do** [comment]
This warning `Fix 'Warning: Each child in a list should have a unique "key" prop` hasn't been fixed
